services:
  app:
    image: ghcr.io/wahadmasridev/lina_website:${APP_TAG:-latest}
    container_name: lina-zakaria-fr
    restart: unless-stopped

    environment:
      - DB_HOST=${DB_HOST:-}
      - DB_NAME=${DB_NAME:-}
      - DB_USER=${DB_USER:-}
      - DB_PASS=${DB_PASS:-}

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      # Router
      - "traefik.http.routers.lina-zakaria-fr.rule=Host(`lina-zakaria.fr`) || Host(`www.lina-zakaria.fr`)"
      - "traefik.http.routers.lina-zakaria-fr.entrypoints=websecure"
      - "traefik.http.routers.lina-zakaria-fr.tls=true"
      - "traefik.http.routers.lina-zakaria-fr.tls.certresolver=le"

      # Service
      - "traefik.http.services.lina-zakaria-fr.loadbalancer.server.port=80"

    networks:
      - proxy

networks:
  proxy:
    external: true
